"""add document_analyses table

Revision ID: 292d5ef07a28
Revises: 0c470aaf77ff
Create Date: 2026-08-07 16:24:09.175170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292d5ef07a28'
down_revision: Union[str, Sequence[str], None] = '0c470aaf77ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('assignees', sa.JSON(), nullable=False),
    sa.Column('deadlines', sa.JSON(), nullable=False),
    sa.Column('importance', sa.String(), nullable=False),
    sa.Column('is_meeting_minutes', sa.Boolean(), nullable=False),
    sa.Column('meeting_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_document_analyses_id'), 'document_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_analyses_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
