"""add erp tables and qa_logs/cross_checks

Revision ID: 6d6c20e72b74
Revises: ee694ef2898a
Create Date: 2026-08-14 11:30:39.482909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6c20e72b74'
down_revision: Union[str, Sequence[str], None] = 'ee694ef2898a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('parent_part_no', sa.String(), nullable=False),
    sa.Column('child_part_no', sa.String(), nullable=False),
    sa.Column('qty_per', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('alt_part_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_erp_bom_child', 'erp_boms', ['organization_id', 'child_part_no'], unique=False)
    op.create_index(op.f('ix_erp_boms_id'), 'erp_boms', ['id'], unique=False)
    op.create_index(op.f('ix_erp_boms_organization_id'), 'erp_boms', ['organization_id'], unique=False)
    op.create_table('erp_inbound_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_inbound_schedules_id'), 'erp_inbound_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_erp_inbound_schedules_organization_id'), 'erp_inbound_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_inbound_schedules_part_no'), 'erp_inbound_schedules', ['part_no'], unique=False)
    op.create_table('erp_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'part_no', name='uq_erp_material_org_part')
    )
    op.create_index(op.f('ix_erp_materials_id'), 'erp_materials', ['id'], unique=False)
    op.create_index(op.f('ix_erp_materials_organization_id'), 'erp_materials', ['organization_id'], unique=False)
    op.create_table('erp_production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('wo_no', sa.String(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_production_plans_id'), 'erp_production_plans', ['id'], unique=False)
    op.create_index(op.f('ix_erp_production_plans_organization_id'), 'erp_production_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_production_plans_wo_no'), 'erp_production_plans', ['wo_no'], unique=False)
    op.create_table('erp_shipment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('so_no', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_shipment_plans_id'), 'erp_shipment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_erp_shipment_plans_organization_id'), 'erp_shipment_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_shipment_plans_so_no'), 'erp_shipment_plans', ['so_no'], unique=False)
    op.create_table('erp_stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=False),
    sa.Column('available_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocated_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_erp_stock_latest', 'erp_stock_snapshots', ['organization_id', 'part_no', 'as_of'], unique=False)
    op.create_index(op.f('ix_erp_stock_snapshots_id'), 'erp_stock_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_erp_stock_snapshots_organization_id'), 'erp_stock_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_stock_snapshots_part_no'), 'erp_stock_snapshots', ['part_no'], unique=False)
    op.create_table('qa_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_logs_id'), 'qa_logs', ['id'], unique=False)
    op.create_table('cross_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qa_log_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('claimed_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('claimed_source', sa.String(), nullable=True),
    sa.Column('claimed_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erp_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('erp_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['qa_log_id'], ['qa_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_checks_id'), 'cross_checks', ['id'], unique=False)
    op.create_index(op.f('ix_cross_checks_qa_log_id'), 'cross_checks', ['qa_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cross_checks_qa_log_id'), table_name='cross_checks')
    op.drop_index(op.f('ix_cross_checks_id'), table_name='cross_checks')
    op.drop_table('cross_checks')
    op.drop_index(op.f('ix_qa_logs_id'), table_name='qa_logs')
    op.drop_table('qa_logs')
    op.drop_index(op.f('ix_erp_stock_snapshots_part_no'), table_name='erp_stock_snapshots')
    op.drop_index(op.f('ix_erp_stock_snapshots_organization_id'), table_name='erp_stock_snapshots')
    op.drop_index(op.f('ix_erp_stock_snapshots_id'), table_name='erp_stock_snapshots')
    op.drop_index('ix_erp_stock_latest', table_name='erp_stock_snapshots')
    op.drop_table('erp_stock_snapshots')
    op.drop_index(op.f('ix_erp_shipment_plans_so_no'), table_name='erp_shipment_plans')
    op.drop_index(op.f('ix_erp_shipment_plans_organization_id'), table_name='erp_shipment_plans')
    op.drop_index(op.f('ix_erp_shipment_plans_id'), table_name='erp_shipment_plans')
    op.drop_table('erp_shipment_plans')
    op.drop_index(op.f('ix_erp_production_plans_wo_no'), table_name='erp_production_plans')
    op.drop_index(op.f('ix_erp_production_plans_organization_id'), table_name='erp_production_plans')
    op.drop_index(op.f('ix_erp_production_plans_id'), table_name='erp_production_plans')
    op.drop_table('erp_production_plans')
    op.drop_index(op.f('ix_erp_materials_organization_id'), table_name='erp_materials')
    op.drop_index(op.f('ix_erp_materials_id'), table_name='erp_materials')
    op.drop_table('erp_materials')
    op.drop_index(op.f('ix_erp_inbound_schedules_part_no'), table_name='erp_inbound_schedules')
    op.drop_index(op.f('ix_erp_inbound_schedules_organization_id'), table_name='erp_inbound_schedules')
    op.drop_index(op.f('ix_erp_inbound_schedules_id'), table_name='erp_inbound_schedules')
    op.drop_table('erp_inbound_schedules')
    op.drop_index(op.f('ix_erp_boms_organization_id'), table_name='erp_boms')
    op.drop_index(op.f('ix_erp_boms_id'), table_name='erp_boms')
    op.drop_index('ix_erp_bom_child', table_name='erp_boms')
    op.drop_table('erp_boms')
    # ### end Alembic commands ###
